export default
[{"id":"rec6d6T3q5EBIdCfD",
"name":"Moscow",
"info":"The Cathedral of Vasily the Blessed (Russian: Собо́р Васи́лия Блаже́нного, tr. Sobór Vasíliya Blazhénnogo), commonly known as Saint Basil's Cathedral, is an Orthodox church in Red Square of Moscow, and is one of the most popular cultural symbols of Russia. The building, now a museum, is officially known as the Cathedral of the Intercession of the Most Holy Theotokos on the Moat, or Pokrovsky Cathedral. It was built from 1555 to 1561 on orders from Ivan the Terrible and commemorates the capture of Kazan and Astrakhan. It was the city's tallest building until the completion of the Ivan the Great Bell Tower in 1600.The original building, known as Trinity Church and later Trinity Cathedral, contained eight chapels arranged around a ninth, central chapel dedicated to the Intercession; a tenth chapel was erected in 1588 over the grave of the venerated local saint Vasily (Basil).",
"image":"https://a.cdn-hotels.com/gdcs/production29/d1375/234f7170-c9f4-4cee-a372-1a198e388483.jpg",
"price":"1,995"},

{"id":"recIwxrvU9HfJR3B4",
"name":"Paris",
"info":"The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower.Locally nicknamed .'La dame de fer' (French for 'Iron Lady'), it was constructed from 1887 to 1889 as the centerpiece of the 1889 World's Fair. Although initially criticised by some of France's leading artists and intellectuals for its design, it has since become a global cultural icon of France and one of the most recognisable structures in the world.[3] The Eiffel Tower is the most visited monument with an entrance fee in the world; 6.91 million people ascended it in 2015. It was designated a monument historique in 1964, and was named part of a UNESCO World Heritage Site ('Paris, Banks of the Seine') in 1991.The tower is 330 metres (1,083 ft) tall,about the same height as an 81-storey building, and the tallest structure in Paris.",
"image":"https://www.planetware.com/photos-large/F/eiffel-tower.jpg",
"price":"3,895"},

{"id":"recJLWcHScdUtI3ny",
"name":"Zambia",
"info":"Victoria Falls (Lozi: Mosi-oa-Tunya, 'The Smoke That Thunders'; Tonga: Shungu Namutitima, 'Boiling Water') is a waterfall on the Zambezi River in southern Africa, which provides habitat for several unique species of plants and animals. It is located on the border between Zambia and Zimbabwe[1] and is one of the world's largest waterfalls, with a width of 1,708 m (5,604 ft).Archeological sites and oral history describe a long record of African knowledge of the site. Though known to some European geographers before the 19th century, Scottish missionary David Livingstone identified the falls in 1855, providing the English colonial name of Victoria Falls after Queen Victoria. Since the mid 20th century, the site has been an increasingly important source of tourism. Zambia and Zimbabwe both have national parks and tourism infrastructure at the site. Research in the late 2010s found that climate change caused precipitation variability is likely to change the character of the fall.",
"image":"https://www.nationsonline.org/gallery/africa/Victoria-Falls-with-rainbow.jpg",
"price":"2,695"},

{"id":"recK2AOoVhIHPLUwn","name":"Best of Rome in 7 Days Tour",
"info":"The Burj Khalifa  Arabic: برج خليفة, Arabic, known as the Burj Dubai prior to its inauguration in 2010, is a skyscraper in Dubai, United Arab Emirates. With a total height of 829.8 m (2,722 ft, or just over half a mile) and a roof height (excluding antenna, but including a 223 m spire[2]) of 828 m (2,717 ft), the Burj Khalifa has been the tallest structure and building in the world since its topping out in 2009, supplanting Taipei 101, the previous holder of that status.Construction of the Burj Khalifa began in 2004, with the exterior completed five years later in 2009. The primary structure is reinforced concrete and some of the structural steel for the building originated from the Palace of the Republic in East Berlin, the former East German parliament. The building was opened in 2010 as part of a new development called Downtown Dubai. It was designed to be the centerpiece of large-scale, mixed-use development. The decision to construct the building was based on the government's decision to diversify from an oil-based economy, and for Dubai to gain international recognition. The building is named in honor of the ruler of Abu Dhabi and president of the United Arab Emirates, Khalifa bin Zayed Al Nahyan;[6] Abu Dhabi and the UAE government lent Dubai money to pay its debts. The building broke numerous height records, including its designation as the tallest building in the world.",
"image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjkj7_p2dEeL6EGO6g6eFq8TGqf1MZ18g7tw&usqp=CAU",
"price":"2,095"},

{"id":"receAEzz86KzW2gvH",
"name":"Egypt",
"info":"The Egyptian pyramids are ancient masonry structures located in Egypt. Sources cite at least 118 identified 'Egyptian' pyramids.Approximately 80 pyramids were built within the Kingdom of Kush, now located in the modern country of Sudan. Of those located in modern Egypt, most were built as tombs for the country's pharaohs and their consorts during the Old and Middle Kingdom periods.The earliest known Egyptian pyramids are found at Saqqara, northwest of Memphis, although at least one step-pyramid-like structure has been found at Saqqara, dating to the First Dynasty: Mastaba 3808, which has been attributed to the reign of Pharaoh Anedjib, with inscriptions, and other archaeological remains of the period, suggesting there may have been others.[6] The otherwise earliest among these is the Pyramid of Djoser built c. 2630 to 2610 BCE during the Third Dynasty.This pyramid and its surrounding complex are generally considered to be the world's oldest monumental structures constructed of dressed masonry.The most famous Egyptian pyramids are those found at Giza, on the outskirts of Cairo. Several of the Giza pyramids are counted among the largest structures ever built.[9] The Pyramid of Khufu is the largest Egyptian pyramid. It is the only one of the Seven Wonders of the Ancient World still in existence, despite its being the oldest wonder by about 2,000 years.",
"image":"https://cdn.mos.cms.futurecdn.net/7YrobQvFFzw8aWsAUtoYXB-1200-80.jpg",
"price":"2,595"}];